Various fixes and updates
- Remove redundant test-requirements and require horizon
  Note: This implies newer versions of django

- Use openstack_dashboard.test.helpers.TestCase
  To fix the following error with py3.
  TypeError: unhashable type: 'TestNeutron_taas_dashboard'

- Update uses of urlresolvers
  See: https://review.openstack.org/#/c/528497/

- Fix ImproperlyConfigured
  See: https://review.openstack.org/#/c/527323/

Change-Id: I60e983baff48cf5bab73c5e89f03b6984ef62417